### ISSUE TITLE
Unexpected signal during execution

### ISSUE THREAD

**Issue by noctivityinc** [lukasmartinelli/pgfutter#43]
Tried to use pgfutter on a new CSV on OSX.

```
08:52 AM ~/Downloads  => pgfutter csv cell_towers.csv
 47.39 MB / 3.10 GB [=>--------------------------------------------------------------------------------------------------]   1.49% 4m8sfatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x35e99]

runtime stack:
runtime.gothrow(0x40e3f0, 0x2a)
	/goroot/src/runtime/panic.go:503 +0x8e fp=0xc208107cd8 sp=0xc208107cc0
runtime.sigpanic()
	/goroot/src/runtime/sigpanic_unix.go:14 +0x5e fp=0xc208107d28 sp=0xc208107cd8
runtime.MSpanList_Remove(0x5e5998)
	/goroot/src/runtime/mheap.c:676 +0x29 fp=0xc208107d30 sp=0xc208107d28
runtime.MCentral_UncacheSpan(0x57f358, 0x5e5998)
	/goroot/src/runtime/mcentral.c:121 +0x7f fp=0xc208107d50 sp=0xc208107d30
runtime.MCache_ReleaseAll(0x5e0000)
	/goroot/src/runtime/mcache.c:111 +0x6a fp=0xc208107d78 sp=0xc208107d50
flushallmcaches()
	/goroot/src/runtime/mgc0.c:1224 +0x61 fp=0xc208107da0 sp=0xc208107d78
markroot(0xc208010000, 0xc200000004)
	/goroot/src/runtime/mgc0.c:536 +0x20a fp=0xc208107e00 sp=0xc208107da0
runtime.parfordo(0xc208010000)
	/goroot/src/runtime/parfor.c:76 +0xb2 fp=0xc208107e80 sp=0xc208107e00
gc(0xc208107fb8)
	/goroot/src/runtime/mgc0.c:1442 +0x25e fp=0xc208107f98 sp=0xc208107e80
runtime.gc_m()
	/goroot/src/runtime/mgc0.c:1371 +0xe0 fp=0xc208107fd0 sp=0xc208107f98
runtime.onM(0xc208012000)
	/goroot/src/runtime/asm_amd64.s:257 +0x68 fp=0xc208107fd8 sp=0xc208107fd0
runtime.mstart()
	/goroot/src/runtime/proc.c:818 fp=0xc208107fe0 sp=0xc208107fd8

goroutine 1 [garbage collection]:
runtime.switchtoM()
	/goroot/src/runtime/asm_amd64.s:198 fp=0xc2080ec790 sp=0xc2080ec788
runtime.gogc(0x0)
	/goroot/src/runtime/malloc.go:469 +0x1cf fp=0xc2080ec7c8 sp=0xc2080ec790
runtime.mallocgc(0x10, 0x0, 0x3, 0x0)
	/goroot/src/runtime/malloc.go:341 +0x391 fp=0xc2080ec878 sp=0xc2080ec7c8
runtime.rawstring(0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/runtime/string.go:195 +0x93 fp=0xc2080ec8a8 sp=0xc2080ec878
runtime.slicebytetostring(0xc208074374, 0xa, 0x40, 0x0, 0x0)
	/goroot/src/runtime/string.go:69 +0x4b fp=0xc2080ec938 sp=0xc2080ec8a8
encoding/csv.(*Reader).parseRecord(0xc208074320, 0xc208141200, 0xc, 0x10, 0x0, 0x0)
	/goroot/src/encoding/csv/reader.go:235 +0x449 fp=0xc2080ec9f8 sp=0xc2080ec938
encoding/csv.(*Reader).Read(0xc208074320, 0x0, 0x0, 0x0, 0x0, 0x0)
	/goroot/src/encoding/csv/reader.go:136 +0x5e fp=0xc2080eca60 sp=0xc2080ec9f8
main.copyCSVRows(0xc208033d60, 0xc208074320, 0x0, 0xc208033746, 0x1, 0xc2080c6100, 0xe, 0x10, 0x0, 0x0, ...)
	/usr/src/pgfutter/csv.go:57 +0xa9 fp=0xc2080ecc08 sp=0xc2080eca60
main.importCSV(0x7fff5fbff2a5, 0xf, 0xc2080e6230, 0x64, 0xc208033500, 0x6, 0x7fff5fbff2a5, 0xb, 0x0, 0x571590, ...)
	/usr/src/pgfutter/csv.go:144 +0x530 fp=0xc2080ece40 sp=0xc2080ecc08
main.func·003(0xc208076a00)
	/usr/src/pgfutter/pgfutter.go:172 +0x332 fp=0xc2080ecf60 sp=0xc2080ece40
runtime.call16(0x440268, 0xc2080360b0, 0x800000008)
	/goroot/src/runtime/asm_amd64.s:401 +0x45 fp=0xc2080ecf78 sp=0xc2080ecf60
reflect.Value.call(0x29e880, 0x440268, 0x13, 0x382790, 0x4, 0xc2080ed3d0, 0x1, 0x1, 0x0, 0x0, ...)
	/goroot/src/reflect/value.go:419 +0x10e5 fp=0xc2080ed290 sp=0xc2080ecf78
reflect.Value.Call(0x29e880, 0x440268, 0x13, 0xc2080ed3d0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/goroot/src/reflect/value.go:296 +0xbc fp=0xc2080ed2f0 sp=0xc2080ed290
github.com/codegangsta/cli.HandleAction(0x29e880, 0x440268, 0xc208076a00, 0x0, 0x0)
	/gopath/src/github.com/codegangsta/cli/app.go:487 +0x2b1 fp=0xc2080ed420 sp=0xc2080ed2f0
github.com/codegangsta/cli.Command.Run(0x38eb70, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3dfcf0, 0x18, 0x0, ...)
	/gopath/src/github.com/codegangsta/cli/command.go:191 +0x10a5 fp=0xc2080ed998 sp=0xc2080ed420
github.com/codegangsta/cli.(*App).Run(0xc2080e8000, 0xc20800a000, 0x3, 0x3, 0x0, 0x0)
	/gopath/src/github.com/codegangsta/cli/app.go:240 +0xa76 fp=0xc2080edc10 sp=0xc2080ed998
main.main()
	/usr/src/pgfutter/pgfutter.go:178 +0xcd3 fp=0xc2080edf98 sp=0xc2080edc10
runtime.main()
	/goroot/src/runtime/proc.go:63 +0xf3 fp=0xc2080edfe0 sp=0xc2080edf98
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080edfe8 sp=0xc2080edfe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x3b610, 0x568bc0, 0x3b1530, 0xf)
	/goroot/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x568bc0, 0x3b1530, 0xf)
	/goroot/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/goroot/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/goroot/src/runtime/proc.go:87 +0x25

goroutine 3 [runnable]:
runtime.Gosched()
	/goroot/src/runtime/proc.go:113 +0x14 fp=0xc20801dfc0 sp=0xc20801dfb0
runtime.bgsweep()
	/goroot/src/runtime/mgc0.go:87 +0x59 fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/goroot/src/runtime/mgc0.c:1386

goroutine 4 [finalizer wait]:
runtime.gopark(0x3b610, 0x571518, 0x3b0e70, 0xe)
	/goroot/src/runtime/proc.go:130 +0x105 fp=0xc208018f30 sp=0xc208018f00
runtime.goparkunlock(0x571518, 0x3b0e70, 0xe)
	/goroot/src/runtime/proc.go:136 +0x48 fp=0xc208018f58 sp=0xc208018f30
runtime.runfinq()
	/goroot/src/runtime/malloc.go:727 +0xba fp=0xc208018fe0 sp=0xc208018f58
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208018fe8 sp=0xc208018fe0
created by runtime.createfing
	/goroot/src/runtime/malloc.go:707 +0x5e

goroutine 5 [syscall]:
runtime.notetsleepg(0x571d20, 0xffffffffffffffff, 0x569901)
	/goroot/src/runtime/lock_sema.go:266 +0x8c fp=0xc20801d768 sp=0xc20801d728
runtime.signal_recv(0x0)
	/goroot/src/runtime/sigqueue.go:109 +0x135 fp=0xc20801d7a0 sp=0xc20801d768
os/signal.loop()
	/goroot/src/os/signal/signal_unix.go:21 +0x1f fp=0xc20801d7e0 sp=0xc20801d7a0
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801d7e8 sp=0xc20801d7e0
created by os/signal.init·1
	/goroot/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
runtime.gopark(0x3b610, 0xc2080926b8, 0x3aded0, 0xc)
	/goroot/src/runtime/proc.go:130 +0x105 fp=0xc2080186b0 sp=0xc208018680
runtime.goparkunlock(0xc2080926b8, 0x3aded0, 0xc)
	/goroot/src/runtime/proc.go:136 +0x48 fp=0xc2080186d8 sp=0xc2080186b0
runtime.chanrecv(0x28c540, 0xc208092660, 0xc2080187c8, 0x1, 0x0)
	/goroot/src/runtime/chan.go:467 +0x82c fp=0xc208018778 sp=0xc2080186d8
runtime.chanrecv2(0x28c540, 0xc208092660, 0xc2080187c8, 0x0)
	/goroot/src/runtime/chan.go:316 +0x2b fp=0xc2080187a8 sp=0xc208018778
database/sql.(*DB).connectionOpener(0xc2080755e0)
	/goroot/src/database/sql/sql.go:589 +0x4c fp=0xc2080187d8 sp=0xc2080187a8
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080187e0 sp=0xc2080187d8
created by database/sql.Open
	/goroot/src/database/sql/sql.go:452 +0x31c

goroutine 7 [syscall]:
runtime.notetsleepg(0x568dd8, 0xbebb461, 0x16)
	/goroot/src/runtime/lock_sema.go:266 +0x8c fp=0xc208017f68 sp=0xc208017f28
runtime.timerproc()
	/goroot/src/runtime/time.go:207 +0xfa fp=0xc208017fe0 sp=0xc208017f68
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208017fe8 sp=0xc208017fe0
created by runtime.addtimerLocked
	/goroot/src/runtime/time.go:113 +0x1ba

goroutine 9 [IO wait]:
runtime.gopark(0x1a080, 0x5f3100, 0x384e50, 0x7)
	/goroot/src/runtime/proc.go:130 +0x105 fp=0xc2080192e0 sp=0xc2080192b0
runtime.netpollblock(0x5f30d8, 0x72, 0xc208126100)
	/goroot/src/runtime/netpoll.go:347 +0x170 fp=0xc208019320 sp=0xc2080192e0
runtime.netpollWait(0x5f30d8, 0x72, 0x8)
	/goroot/src/runtime/netpoll.go:150 +0x68 fp=0xc208019340 sp=0xc208019320
net.(*pollDesc).Wait(0xc2080e6060, 0x72, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:84 +0x47 fp=0xc208019360 sp=0xc208019340
net.(*pollDesc).WaitRead(0xc2080e6060, 0x0, 0x0)
	/goroot/src/net/fd_poll_runtime.go:89 +0x43 fp=0xc208019388 sp=0xc208019360
net.(*netFD).Read(0xc2080e6000, 0xc2080c8000, 0x1000, 0x1000, 0x0, 0x5f1cc0, 0xc2081260f8)
	/goroot/src/net/fd_unix.go:242 +0x40f fp=0xc208019428 sp=0xc208019388
net.(*conn).Read(0xc208036030, 0xc2080c8000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/goroot/src/net/net.go:121 +0xdc fp=0xc208019470 sp=0xc208019428
bufio.(*Reader).fill(0xc208092180)
	/goroot/src/bufio/bufio.go:97 +0x1ce fp=0xc208019518 sp=0xc208019470
bufio.(*Reader).Read(0xc208092180, 0xc208054020, 0x5, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/bufio/bufio.go:174 +0x26c fp=0xc2080195b0 sp=0xc208019518
io.ReadAtLeast(0x5f31c0, 0xc208092180, 0xc208054020, 0x5, 0x200, 0x5, 0x0, 0x0, 0x0)
	/goroot/src/io/io.go:298 +0xf1 fp=0xc208019608 sp=0xc2080195b0
io.ReadFull(0x5f31c0, 0xc208092180, 0xc208054020, 0x5, 0x200, 0x0, 0x0, 0x0)
	/goroot/src/io/io.go:316 +0x6d fp=0xc208019658 sp=0xc208019608
github.com/lib/pq.(*conn).recvMessage(0xc208054000, 0xc20811d0c0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/lib/pq/conn.go:892 +0x17a fp=0xc208019728 sp=0xc208019658
github.com/lib/pq.(*copyin).resploop(0xc2080383c0)
	/gopath/src/github.com/lib/pq/copy.go:143 +0x55 fp=0xc2080197d8 sp=0xc208019728
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e0 sp=0xc2080197d8
created by github.com/lib/pq.(*conn).prepareCopyIn
	/gopath/src/github.com/lib/pq/copy.go:90 +0xae5

goroutine 10 [select]:
runtime.gopark(0x1ebd0, 0xc208019f40, 0x39afb0, 0x6)
	/goroot/src/runtime/proc.go:130 +0x105 fp=0xc208019d58 sp=0xc208019d28
runtime.selectgoImpl(0xc208019f40, 0x0, 0x18)
	/goroot/src/runtime/select.go:366 +0xb2c fp=0xc208019ef0 sp=0xc208019d58
runtime.selectgo(0xc208019f40)
	/goroot/src/runtime/select.go:183 +0x12 fp=0xc208019f10 sp=0xc208019ef0
github.com/cheggaaa/pb.(*ProgressBar).refresher(0xc208076000)
	/gopath/src/github.com/cheggaaa/pb/pb.go:423 +0xff fp=0xc208019fd8 sp=0xc208019f10
runtime.goexit()
	/goroot/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208019fe0 sp=0xc208019fd8
created by github.com/cheggaaa/pb.(*ProgressBar).Start
	/gopath/src/github.com/cheggaaa/pb/pb.go:123 +0xcd
```

**Comment by dacoinminster** [comment]
Try installing from source (issue #31)
