### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by Doctorrr** [lukasmartinelli/pgfutter#79]
15Mb CSV file:

`panic: runtime error: index out of range

goroutine 1 [running]:
main.copyCSVRows(0xc4200459a0, 0xc420056b40, 0x0, 0x73fa7a, 0x1, 0xc42017a000, 0x31, 0x40, 0xc4200459a0, 0x0, ...)
	/usr/src/pgfutter/csv.go:99 +0x747
main.importCSV(0x7fffb31bc2c1, 0x30, 0xc420066100, 0x71, 0x7fffb31bc293, 0x6, 0xc420014770, 0x5, 0x0, 0x0, ...)
	/usr/src/pgfutter/csv.go:172 +0x3f6
main.main.func2(0xc4200b2420, 0xc420079200, 0xc4200b2420)
	/usr/src/pgfutter/pgfutter.go:164 +0x38f
github.com/codegangsta/cli.HandleAction(0x6e19c0, 0x7586c8, 0xc4200b2420, 0x0, 0xc4200588a0)
	/gopath/src/github.com/codegangsta/cli/app.go:501 +0xd2
github.com/codegangsta/cli.Command.Run(0x73fda9, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x74b480, 0x18, 0x0, ...)
	/gopath/src/github.com/codegangsta/cli/command.go:165 +0x4bb
github.com/codegangsta/cli.(*App).Run(0xc420108000, 0xc4200100f0, 0xf, 0xf, 0x0, 0x0)
	/gopath/src/github.com/codegangsta/cli/app.go:259 +0x740
main.main()
	/usr/src/pgfutter/pgfutter.go:170 +0xcce
`

**Comment by ThomasSchoeller** [comment]
Hey @lukasmartinelli 
you should merge this PR. i had the described problem and with the fork from the0rem it is working great!
BR
Thomas
